# Generated by Django 5.2.7 on 2025-10-15 21:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Control_Access', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('CNPJ', models.CharField(max_length=14, unique=True)),
                ('data_nascimento', models.DateField()),
                ('telefone', models.CharField(max_length=15)),
                ('endereco', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='processo_administrativo',
            fields=[
                ('protocolo', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('data_criacao', models.DateField(auto_now_add=True)),
                ('status', models.CharField(max_length=50)),
                ('descricao', models.TextField()),
                ('tipo', models.CharField(choices=[('1', 'Licenciamento'), ('2', 'Denúncia')], max_length=1)),
                ('data_conclusao', models.DateField(blank=True, null=True)),
                ('user_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Administrador',
        ),
    ]
