# Generated by Django 5.2.7 on 2025-10-16 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Control_Access', '0002_usuario_processo_administrativo_delete_administrador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processo_administrativo',
            name='status',
            field=models.CharField(choices=[('FE', 'Está na fila de espera'), ('V', 'À ser vistoriado'), ('A', 'Em análise'), ('C', 'Concluído'), ('Ar', 'Arquivado')], max_length=20),
        ),
        migrations.AlterField(
            model_name='processo_administrativo',
            name='tipo',
            field=models.CharField(choices=[('1 - Licenciamento', 'Licenciamento'), ('2 - Denúncia ', 'Denúncia')], max_length=20),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='CNPJ',
            field=models.CharField(blank=True, max_length=14, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='cpf',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True),
        ),
    ]
